---
- name: Copy configs files 
  template: 
    src: "{{ item }}.j2"
    dest: "/etc/asterisk/{{ item }}.conf"
  with_items:
    - acl.conf
    - cdr_tds.conf
    - extconfig.conf
    - mgcp.conf
    - res_odbc.conf
    - adsi.conf
    - cel.conf
    - extensions.ael
    - minivm.conf
    - res_pgsql.conf
    - agents.conf
    - cel_custom.conf
    - extensions.conf
    - misdn.conf
    - res_pktccops.conf
    - alarmreceiver.conf
    - cel_odbc.conf
    - extensions.lua
    - modules.conf
    - res_snmp.conf
    - alsa.conf
    - cel_pgsql.conf
    - extensions_minivm.conf
    - motif.conf
    - res_stun_monitor.conf
    - amd.conf
    - cel_sqlite3_custom.conf
    - features.conf
    - musiconhold.conf
    - rtp.conf
    - app_mysql.conf
    - cel_tds.conf
    - festival.conf
    - muted.conf
    - say.conf
    - app_skel.conf
    - chan_dahdi.conf
    - followme.conf
    - ooh323.conf
    - sip.conf
    - asterisk.adsi
    - chan_mobile.conf
    - func_odbc.conf
    - osp.conf
    - sip_notify.conf
    - asterisk.conf
    - cli.conf
    - gtalk.conf
    - oss.conf
    - skinny.conf
    - calendar.conf
    - cli_aliases.conf
    - h323.conf
    - phone.conf
    - sla.conf
    - ccss.conf
    - cli_permissions.conf
    - http.conf
    - phoneprov.conf
    - smdi.conf
    - cdr.conf
    - codecs.conf
    - iax.conf
    - queuerules.conf
    - telcordia-1.adsi
    - cdr_adaptive_odbc.conf
    - confbridge.conf
    - iaxprov.conf
    - queues.conf
    - udptl.conf
    - cdr_custom.conf
    - config_test.conf
    - indications.conf
    - res_config_mysql.conf
    - unistim.conf
    - cdr_manager.conf
    - console.conf
    - jabber.conf
    - res_config_sqlite.conf
    - users.conf
    - cdr_mysql.conf
    - dbsep.conf
    - jingle.conf
    - res_config_sqlite3.conf
    - voicemail.conf
    - cdr_odbc.conf
    - dnsmgr.conf
    - logger.conf
    - res_corosync.conf
    - vpb.conf
    - cdr_pgsql.conf
    - dsp.conf
    - manager.conf
    - res_curl.conf
    - xmpp.conf
    - cdr_sqlite3_custom.conf
    - dundi.conf
    - meetme.conf
    - res_fax.conf
    - cdr_syslog.conf
    - enum.conf
    - menuselect.makeopts
    - res_ldap.conf
  tags: asterisk-config
  notify: Restart Asterisk
  