---
#Update and upgrade apt-based linux
- name: Update and upgrade apt-based Linux
  apt: update-cache=yes state=latest
  apt: upgrade=full
  sudo: yes

- name: install linux linux-headers
  action: shell apt-get install -y linux-headers-$(uname -r)
#  ignore_errors: True
#  tags:


- name: check if a reboot is required
  shell: "[ -f /var/run/reboot-required ]"
  failed_when: False
  register: reboot_required
  changed_when: reboot_required.rc == 0
  notify: reboot

#  handler:
#  - name: reboot
#    command: shutdown -r now "Ansible updates triggered"
#    async: 0
#    poll: 0
#    ignore_errors: true

