- name: Install PGsql server and client
  apt: pkg={{ item }}
  sudo: yes
  with_items:
        - libossp-uuid16
        - libpq5
        - libxslt1.1
        - postgresql
        - postgresql-client
        - postgresql-client-common
        - postgresql-common
        - postgresql-client
        - postgresql-contrib
        - libpq-dev

- name: Start pgsql
  service: name=postgresql state=restarted
  sudo: yes
